#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

		[types.cake.nomansland]
			fruit_cake = true

		[types.lantern.suppsquared]
			copper_lantern = true
			brass_lantern = true
			crimson_lantern = true

		[types.lantern.caverns_and_chasms]
			cupric_lantern = true
			copper_lantern = true
			exposed_copper_lantern = true
			weathered_copper_lantern = true
			oxidized_copper_lantern = true
			waxed_copper_lantern = true
			waxed_exposed_copper_lantern = true
			waxed_weathered_copper_lantern = true
			waxed_oxidized_copper_lantern = true

		[types.lantern.enderscape]
			bulb_lantern = true

		[types.wood_type.abundant_atmosphere]
			red_bamboo = true
			ashroot = true
			gourdrot = true

		[types.wood_type.caverns_and_chasms]
			azalea = true

		[types.wood_type.unusualend]
			chorus_nest = true

		[types.wood_type.places]
			plastic = true

		[types.wood_type.nomansland]
			pine = true
			maple = true
			walnut = true
			willow = true

		[types.wood_type.environmental]
			willow = true
			pine = true
			plum = true
			wisteria = true

		[types.wood_type.enderscape]
			veiled = true
			celestial = true
			murublight = true

		[types.wood_type.spawn]
			rotten = true
			date = true

		[types.leaves_type.abundant_atmosphere]
			ashroot = true
			gourdrot = true

		[types.leaves_type.nomansland]
			yellow_birch = true
			autumnal_oak = true
			pale_cherry = true
			frosted = true
			pine = true
			maple = true
			red_maple = true
			walnut = true
			willow = true
			apple_fruit = true
			pear_fruit = true

		[types.leaves_type.environmental]
			hibiscus = true
			willow = true
			pine = true
			plum = true
			cheerful_plum = true
			moody_plum = true
			wisteria = true
			pink_wisteria = true
			blue_wisteria = true
			purple_wisteria = true
			white_wisteria = true

		[types.leaves_type.spawn]
			date = true

#Disables specific entries
[entries]

		[entries.wood_type.nomansland]
			bookshelf = true
			trimmed_planks = true

		[entries.wood_type.another_furniture]
			table = true
			flower_box = true
			shelf = true
			drawer = true
			shutter = true
			bench = true
			chair = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.dramaticdoors]
			short_door = true
			tall_door = true
