[rendering]
	bladesPerBlock = 32
	bladeHeight = 0.35
	heightVariation = 1.0
	bladeWidth = 1.2
	renderRadius = 120
	grassStyle = "SEGMENTED"
	grassBrightness = 1.0
	bladeGradientBottom = 1.0
	bladeGradientTop = 1.1
	bladeGradientCurve = 1.5
	windSpeed = 20
	windDirectionDegrees = 0.0
	dynamicWind = true

[plants]
	plantBlacklist = ["minecraft:sea_pickle", "minecraft:seagrass", "minecraft:tall_seagrass", "nomansland:apple", "nomansland:cave_weeds", "nomansland:pear"]
	plantWhitelist = ["environmental:giant_tall_grass=3", "nomansland:grass_sprouts=0.6"]
	modEnabled = true
	distantVanillaPlants = true
	distanceFalloff = "EXPONENTIAL"
	wavingLeaves = true
	leafSwayAmount = 0.35
	leafRenderRadius = 100
	bambooSway = true
	bambooSwayAmount = 0.5
	bambooRenderRadius = 32
