#Truly Dark properties file
#Mon Jul 20 14:16:44 EDT 2026
biome_blacklist=alexscaves\:primordial_caves,alexscaves\:candy_cavity
cloud_darkness=0.1
dark_default=true
dark_end=false
dark_end_fog=0.0
dark_moon=true
dark_nether=false
dark_nether_fog=0.5
dark_overworld=true
dark_sky=false
dark_skyless=true
entity_light_floor=0.05
fog_darkness=0.1
hard_lock=false
ignore_moon_phase=false
moon_phase_intensity=0.8500000000000001
only_affect_block_light=false
pack_configured=false
require_client_mod=false
setup_version=Manual
sky_darkness=0.5
sky_merge=true
